import Head from 'next/head'
import { Inter } from '@next/font/google'
import HomeContainer from './vehicle'
import Form from './vehicle/Form'
import { GetServerSideProps} from 'next'
import styles from '../styles/Home.module.css'
import { prisma } from '../Library/prisma'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

interface  Vehicles{
  vehicle:{
    id: string
    vehicleName: string
    vehicleModel: string
    numberOfWheels: string
  }[]
}

export default function Home({vehicle}: Vehicles) {
  const router = useRouter();
  const refreshData = () =>{
    router.replace(router.asPath)
  }

  async function deleteVehicle(id: string) {        
    try{
        fetch(`http://localhost:3000/api/vehicle/${id}`,{
             headers: {
                'Content-Type' : 'application/json'
            },
            method: 'DELETE'
        }).then(() => {
               
                refreshData()
            }
            )
        
    }catch(error){
        console.log(error)
    }
}
  return (
    <>
      <Head>
        <title>Vehicle Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='content'>
         <div>
            <Form />
         </div>
         <div>
         <div className={styles.container}>
            <h2>Registered Vehicles</h2>
            <div className={styles.inner}>
              <ul>
                  {vehicle.map(vehicle=>(
                    <li key={vehicle.id} className={styles.list} >
                      <div  className={styles.data}>
                        <div className=''>
                          <p>{vehicle.vehicleName}</p>
                          <p>{vehicle.vehicleModel}</p>
                          <p>{vehicle.numberOfWheels}</p>
                          <div className=''>
                            <button className={styles.update}>Update</button>
                            <button className={styles.delete} onClick={()=>deleteVehicle(vehicle.id)}>Delete</button>
                          </div>
                          <hr className={styles.line}/>
                        </div>
                      </div>
                    </li>
                  ))}
              </ul>

            </div>
              
          </div>
         </div>
        </div>
    </>
  )
}

//implementation to access database data 
export const getServerSideProps: GetServerSideProps = async () => {
  const vehicle = await prisma.vehicleData.findMany({
    select: {
      vehicleName: true,
      vehicleModel: true,
      numberOfWheels: true,
      id:true
    }
  })
  return{
    props:{
      vehicle
    }
  }
}